### PR TITLE
Add Developer Tools

### PR DESCRIPTION
**Pull request by ryanRfox**
This PR adds:
- [x] EnableDeveloperAPI:true to config.ini for `algod`
- [x] **tealdbg** command to `sandbox`
- [ ] Docker port forwarding 9392:9392

### CODE REVIEW

**Comment by ryanRfox** [comment]
I am unable to connect to **localhost:9392** using the Chrome Debugging Tool after executing the following commands:
```
./sandbox up testnet  
./sandbox goal app call --app-id $APP_ID --from $USER --dryrun-dump --out dryrun-dump.json
./sandbox tealdbg debug --dryrun-req dryrun-dump.json 
```

The Docker image is successfully created, 1. sets EnableDeveloperAPI to allow _dryrun_ and _compile_ endpoints, 2. exposes **tealdbg** to `sandbox`, builds transactions and dryrun-request objects, and launches the `tealdbg` daemon:

```
2020/09/24 21:46:40 Using proto: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
2020/09/24 21:46:40 ------------------------------------------------
2020/09/24 21:46:40 CDT debugger listening on: ws://localhost:9392/3ed64d1e4c83ff7c769846078ab724c4ebedf58cbf2b757abd14ebb72ed1daee
2020/09/24 21:46:40 Or open in Chrome:
2020/09/24 21:46:40 devtools://devtools/bundled/js_app.html?experiments=true&v8only=false&ws=localhost:9392/3ed64d1e4c83ff7c769846078ab724c4ebedf58cbf2b757abd14ebb72ed1daee
2020/09/24 21:46:40 ------------------------------------------------
```

However,  the CDT is unable to connect to neither `devtools://` nor `chrome://inspect`. I've attempted including the `--remote-debugging-port` flag and modifying the port assignment within the `sandbox` source as well. I'm not sure how to troubleshoot the port forwarding bits to confirm my Docker image is built properly.

**Comment by aldur** [comment]
I did some experiments with this and I think the issue is that, at that time, `tealdbg` was listening on the loopback interface only. This should now be fixed by [this commit](https://github.com/algorand/go-algorand/blame/310e05a092284becbb5b761152c25e344860aba8/cmd/tealdbg/main.go#L150). 

I have rebased your branch against the current `master`, but it ships with the old version of `tealdbg`; I think it should be possible to have it pull from `go-algorand` / `master`, but did not try it yet.

Hope it helps! :)

**Comment by aldur** [comment]
Update: I have pushed the rebased branch [here](https://github.com/aldur/sandbox/tree/aldur/add-tealdbg).

I was able to test it as follows:

```bash
sandbox up dev

...

sandbox goal clerk dryrun -t combined.txn.sig --dryrun-dump -o dr.msgp
sandbox tealdbg --listen 0.0.0.0 debug $TEAL_APPROVAL_PROG -d dr.msgp --group-index 0
```

Note that it's still a partial results as, for some reason, CDT can't parse the source map (which loops OK if I pipe it to `jq` through `curl`).

Screenshot 2021-04-02 at 10 37 53

**Comment by aldur** [comment]
Just a quick update: I got it working by replacing the pattern `0.0.0.0` from the `devtools` connection string to `127.0.0.1` on the host (macOS, in my case).

e.g.:

```txt
devtools://devtools/bundled/js_app.html?experiments=true&v8only=false&ws=0.0.0.0:9392/71f774fb569451684ac03b794898a4dd788b4e89095df24835e2510124e0aa97
``` 

will become:

```txt
devtools://devtools/bundled/js_app.html?experiments=true&v8only=false&ws=127.0.0.1:9392/71f774fb569451684ac03b794898a4dd788b4e89095df24835e2510124e0aa97
```

**Comment by yaovi-a** [comment]
No longer an issue. Good to close.

**Pull request closed without merging**
